name: NekoPlugin
version: 1.0.0-SNAPSHOT
main: com.nyarutoru.nekoplugin.NekoPlugin
description: A plugin for PaperMC server
api-version: '26.2'
folia-supported: true
permissions:
  nekoplugin.grave.use:
    description: Allows players to list and open their graves
    default: true
  nekoplugin.grave.admin:
    description: Allows access to and management of all graves
    default: op
